### ISSUE TITLE
nanonisTCP - add oscilloscope module?

### ISSUE THREAD

**Issue by emmaberger11** [New-Horizons-SPM/nanonisTCP#17]
I have found your code for controlling Nanonis quite helpful. I wonder if you can add code that controls the oscilloscope 2-channel module (starting on page 212 of Nanonis TCP manual). I have an external lock-in that plugs into one of the analog inputs of the Nanonis. After talking with SPECS, they say that the fastest way to grab data from this external lock-in is to use the oscilloscope. It would be very helpful for me if you could add this module to your library.

**Comment by ceds92** [comment]
Hi! I'm glad you're finding it useful :). I can add this when I return from holidays in early January.

**Comment by ceds92** [comment]
I've added the [Oscilloscope 2-Channel module](https://github.com/New-Horizons-SPM/nanonisTCP/releases/tag/v1.0.1).
